/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static class GroceryCounter {
        private int count;
        private int overflowCount;

        public GroceryCounter() {
            count = 0;
            overflowCount = 0;
        }

        public void tens() {
            count += 1000;

            if (count > 9999) {
                count -= 10000;
                overflowCount++;
            }
        }

        public void ones() {
            count += 100;

            if (count > 9999) {
                count -= 10000;
                overflowCount++;
            }
        }

        public void tenths() {
            count += 10;

            if (count > 9999) {
                count -= 10000;
                overflowCount++;
            }
        }

        public void hundreths() {
            count += 1;

            if (count > 9999) {
                count -= 10000;
                overflowCount++;
            }
        }

        public String total() {
            int dollars = count / 100;
            int cents = count % 100;

            return String.format("$%d.%02d", dollars, cents);
        }

        public int overflows() {
            return overflowCount;
        }

        public void clear() {
            count = 0;
            overflowCount = 0;
        }
    }
    public static void main(String[] args) {

        GroceryCounter counter = new GroceryCounter();

        System.out.println(counter.total());

        counter.tens();
        counter.tens();
        counter.hundreths();

        System.out.println(counter.total());
        System.out.println(counter.overflows());

        for (int i = 0; i < 35; i++) {
            counter.ones();
        }

        System.out.println(counter.total());
        System.out.println(counter.overflows());

        for (int i = 0; i < 100; i++) {
            counter.ones();
        }

        System.out.println(counter.total());
        System.out.println(counter.overflows());

        counter.clear();

        System.out.println(counter.total());
        System.out.println(counter.overflows());
    }
}

/*GroceryCounter counter = new GroceryCounter();
 
System.out.println(counter.total()); // This would print out $0.00
 
counter.tens();
counter.tens();
counter.hundreths();
 
System.out.println(counter.total()); // This would print out $20.01
System.out.println(counter.overflows()); // This would print out 0
 
for(int i = 0; i < 35; i++) {
  counter.ones();
}
 
System.out.println(counter.total()); // This would print out $55.01
System.out.println(counter.overflows()); // This would print out 0
 
for(int i = 0; i < 100; i++) {
  counter.ones();
}
 
System.out.println(counter.total()); // This would print out $55.01
System.out.println(counter.overflows()); // This would print out 1
 
counter.clear();
 
System.out.println(counter.total()); // This would print out $0.00
System.out.println(counter.overflows()); // This would print out 0
 */
//example