/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  // This is a sample test to show you how everything works
  // You should delete this file / test and then implement your own
  // @Test
  // void appHasAGreeting() {
  //   App classUnderTest = new App();
  //   assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  // }

    //tests if the counter starts correctly at 0
    @Test
    void counterStartsAtZero() {
        App.GroceryCounter counter = new App.GroceryCounter();

        assertEquals("$0.00", counter.total());
        assertEquals(0, counter.overflows());
    }

    //test if the counter correctly increments by 10$
    @Test
    void tensIncrementsByTenDollars() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.tens();

        assertEquals("$10.00", counter.total());
    }

    //tests if the counter works correctly when incrementing by 1$
    @Test
    void onesIncrementsByOneDollar() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.ones();

        assertEquals("$1.00", counter.total());
    }

    //tests if the counter works correctly when incrementing by 10 cents
    @Test
    void tenthsIncrementsByTenCents() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.tenths();

        assertEquals("$0.10", counter.total());
    }

    //tests if the counter works correctly when incrementing by 1 cent
    @Test
    void hundrethsIncrementsByOneCent() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.hundreths();

        assertEquals("$0.01", counter.total());
    }

    //tets if the counter works corretly when incremented by mulitple and different counters
    @Test
    void multipleButtonsWorkTogether() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.tens();
        counter.tens();
        counter.hundreths();

        assertEquals("$20.01", counter.total());
        assertEquals(0, counter.overflows());
    }

    //tests if the counter will overflow (1)
    @Test
    void counterOverflows() {
        App.GroceryCounter counter = new App.GroceryCounter();

        for (int i = 0; i < 10000; i++) {
            counter.hundreths();
        }

        assertEquals("$0.00", counter.total());
        assertEquals(1, counter.overflows());
    }

    //tests if counter.clear will clear the counter
    @Test
    void clearResetsCounter() {
        App.GroceryCounter counter = new App.GroceryCounter();

        counter.tens();
        counter.ones();
        counter.tenths();
        counter.hundreths();

        counter.clear();

        assertEquals("$0.00", counter.total());
        assertEquals(0, counter.overflows());
    }

    //tests if clear still works even when the counter is overflowed
    @Test
    void clearResetsOverflowCount() {
        App.GroceryCounter counter = new App.GroceryCounter();

        for (int i = 0; i < 10000; i++) {
            counter.hundreths();
        }

        counter.clear();

        assertEquals(0, counter.overflows());
        assertEquals("$0.00", counter.total());
    }
}